### ISSUE TITLE
IR transmitter

### ISSUE THREAD

**Issue by Jaco-VanderMerwe** [nitaybz/homebridge-switchbee#4]
Great work with this plugin! 
I have the Switchbee plug sockets with the IR transmitters, and I use these to trigger prefined actions on my AC e.g. turn off / turn on in predefined mode / set to certain temperature, etc.
However, the IR capabilities are not currently visible through the Homebridge plugin. Is it perhaps possible to expose these IR features as well please?

**Comment by nitaybz** [comment]
Maybe in the future, but not at the moment... sorry...

**Comment by nitaybz** [comment]
Added to the latest version
