### ISSUE TITLE
There is no way to get a password

### ISSUE THREAD

**Issue by tomer2526** [nitaybz/homebridge-switchbee#5]
Hello,
I just discovered Homebridge and the plugin that was most important to me is this plugin.
Unfortunately I encountered a problem while setting up this plugin:
There is no way to get a password, in the Switchbee application there is an option to add users but users do not have a password, they have a temporary code used for a one-time password (I tried to enter this code as a password but it did not work)

**Comment by miaszh** [comment]
try [this](https://github.com/nitaybz/homebridge-switchbee/issues/1#issuecomment-771903059) - Issue #1

**Comment by nitaybz** [comment]
Try to set Password from User screen (Details tab), click on Edit to see the Set Password field, make sure to do it from the following apps:
Voltex Smart Touch on iPhone
or
SwitchBee on Android

**Comment by miaszh** [comment]
> Hello, I just discovered Homebridge and the plugin that was most important to me is this plugin. Unfortunately I encountered a problem while setting up this plugin: There is no way to get a password, in the Switchbee application there is an option to add users but users do not have a password, they have a temporary code used for a one-time password (I tried to enter this code as a password but it did not work)

Take a look at issue #6 , Anyway, your Central Unit should have version 1.4.0(4) at least for the plugin to work according to the repository owner, and you can perform an update with Semicom support 072-3942535, they will only need your CU's MAC.

**Comment by tomer2526** [comment]
> Try to set Password from User screen (Details tab), click on Edit to see the Set Password field, make sure to do it from the following apps: Voltex Smart Touch on iPhone or SwitchBee on Android

Excuse me for answering after a long time, I was finally able to add the SwitchBee devices to HomeKit thanks to this great plugin!
I will attach photos to make it easier for other people to identify the location of the password (because I found another area to create a password and another area that has a temporary password and I did not realize there is another area where the password is created for this plugin).
<img width="1200" alt="2022-05-09_21-16-03" src="https://user-images.githubusercontent.com/32513840/167475214-352ab18a-cb81-44f9-8db0-53ee6ce0db44.png">
<img width="1200" alt="2022-05-09_21-18-03" src="https://user-images.githubusercontent.com/32513840/167475267-6a65f020-91d1-4d46-853c-90e7d46c90e3.png">

**Comment by nitaybz** [comment]
Instructions now available in the readme:
https://github.com/nitaybz/homebridge-switchbee#how-to-get-password
